trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChocoPlanet.Models;

namespace ChocoPlanet.Controllers
{
    public class AdministratorController : Controller
    {
       
        public AdministratorController()
        {
            
        }


        public ActionResult ListOptions()
        {
            return View();
        }

    }
}

trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChocoPlanet.Core;
using ChocoPlanet.Models;


namespace ChocoPlanet.Controllers
{
    [HandleErrors]
    public class OrderController : Controller
    {
        private ChocoPlanetDbEntities chocoPlanetDbEntities;

        public OrderController(ChocoPlanetDbEntities chocoPlanetDbEntities)
        {
            this.chocoPlanetDbEntities = chocoPlanetDbEntities;
        }

        [Authorize(Roles = "Администратори")]
        public ActionResult Index()
        {
            return View(chocoPlanetDbEntities.Order);
        }

        [Authorize(Roles = "Администратори")]
        public ActionResult Details(int id)
        {

            return View(chocoPlanetDbEntities.Order.SingleOrDefault(o => o.ID == id));
        }
        [HttpGet]
        [Authorize(Roles = "Администратори")]
        public ActionResult Edit(int id)
        {
            ViewData["Status"] = new SelectList(chocoPlanetDbEntities.Status, "ID", "Name");
            return View(chocoPlanetDbEntities.Order.SingleOrDefault(o => o.ID == id));
        }
        [HttpPost]
        [Authorize(Roles = "Администратори")]
        public ActionResult Edit(int id, Order ordersInfo)
        {
            Order order = chocoPlanetDbEntities.Order.SingleOrDefault(o => o.ID == ordersInfo.ID);
            order.ModifayDate = DateTime.Now;
            order.StatusId = ordersInfo.StatusId;
            order.Customer.Name = ordersInfo.Customer.Name;
            order.Customer.Telefon = ordersInfo.Customer.Telefon;
            order.Customer.Address.Stret = ordersInfo.Customer.Address.Stret;
            order.Customer.Address.Town = ordersInfo.Customer.Address.Town;
            order.Customer.Address.Country.Name = ordersInfo.Customer.Address.Country.Name;
            chocoPlanetDbEntities.SaveChanges();

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Администратори")]
        public ActionResult Delete(int id)
        {
            Order order = chocoPlanetDbEntities.Order.SingleOrDefault(o => o.ID == id);
            foreach (OrderItems items in chocoPlanetDbEntities.OrderItems.Where(i => i.OrderId == id))
            {
                chocoPlanetDbEntities.OrderItems.DeleteObject(items);
            }
            chocoPlanetDbEntities.Order.DeleteObject(order);
            // chocoPlanetDbEntities.Order.DeleteObject(order);
            chocoPlanetDbEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Администратори")]
        public ActionResult RemoveItems(int id, int orderId)
        {
            OrderItems orderItems = chocoPlanetDbEntities.OrderItems.SingleOrDefault(p => p.ID == orderId);
            chocoPlanetDbEntities.OrderItems.DeleteObject(orderItems);
            chocoPlanetDbEntities.SaveChanges();
            return RedirectToAction("Details", new { id = id });
        }
        [Authorize(Roles = "Администратори")]
        public ActionResult Add(int id, int orderId)
        {
            OrderItems orderItems = chocoPlanetDbEntities.OrderItems.SingleOrDefault(p => p.ID == orderId);
            orderItems.Quantity++;
            chocoPlanetDbEntities.SaveChanges();
            return RedirectToAction("Details", new { id = id });
        }
        [Authorize(Roles = "Администратори")]
        public ActionResult Minus(int id, int orderId)
        {
            OrderItems orderItems = chocoPlanetDbEntities.OrderItems.SingleOrDefault(p => p.ID == orderId);
            orderItems.Quantity--;
            chocoPlanetDbEntities.SaveChanges();
            return RedirectToAction("Details", new { id = id });
        }

    }
}

trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChocoPlanet.Core;
using ChocoPlanet.Models;
using ChocoPlanet.Models.File;

namespace ChocoPlanet.Controllers
{
    [HandleErrors]
    public class ProductController : Controller
    {
        //private readonly DataManager _dataManager;
        private readonly ChocoPlanetDbEntities chocoPlanetDbEntities;


        private ViewResult viewResultProduct;
        private IFileStore _fileStore = new DiskFileStore();
        public int PageSize = 1;
        public ViewResult ViewResultProduct { get; private set; }


        public string GetFileName()
        {

            return _fileStore.SaveUploadedFile(Request.Files[0]);
        }
        public ProductController(ChocoPlanetDbEntities chocoPlanetDbEntities)
        {

            this.chocoPlanetDbEntities = chocoPlanetDbEntities;


        }

        public ActionResult ProductCatalog(string category, int page)
        {
            int categoryId = 0;
            IQueryable<Product> productsInCategory;
            if (!string.IsNullOrEmpty(category))
            {
                categoryId = chocoPlanetDbEntities.Category.SingleOrDefault(c => c.Name == category).ID;
            }
            productsInCategory =
                GetAllProductOrFilter(categoryId).OrderBy(x => x.ID).Skip((page - 1) * PageSize).Take(PageSize);

            ViewResultProduct = View(productsInCategory.ToList());
            int numProduct = GetAllProductOrFilter(categoryId).Count();
            ViewData["TotalPages"] = (int)Math.Ceiling((double)numProduct / PageSize);
            ViewData["CurrentPage"] = page;

            ViewData["CurrentCategory"] = (string.IsNullOrEmpty(category)) ? string.Empty : chocoPlanetDbEntities.Category.SingleOrDefault(p => p.ID == categoryId).Name;

            return ViewResultProduct;

        }
        [Authorize(Roles = "Администратори")]
        public ActionResult SecurityProductCatalog([Bind(Include = "ID")]Category category)
        {
            ViewData["ID"] = new SelectList(chocoPlanetDbEntities.Category, "ID", "Name");
            ViewResultProduct = View(GetAllProductOrFilter(category.ID));
            return ViewResultProduct;
        }
        [HttpGet]
        [Authorize(Roles = "Администратори")]
        public ActionResult Edit(int id)
        {
            Product product = chocoPlanetDbEntities.Product.SingleOrDefault(p => p.ID == id);
            ViewData["Category"] = new SelectList(chocoPlanetDbEntities.Category, "ID", "Name"); ;
            return View(chocoPlanetDbEntities.Product.SingleOrDefault(p => p.ID == id));
        }
        [HttpPost]
        [Authorize(Roles = "Администратори")]
        public ActionResult Edit(int id, Product product, string photo_filename)
        {
            Product _product = chocoPlanetDbEntities.Product.SingleOrDefault(p => p.ID == product.ID);
            _product.Name = product.Name;
            if (!String.IsNullOrEmpty(photo_filename))
                _product.Foto = _fileStore.UploadFolderAbsolute + photo_filename;
            _product.Price = product.Price;
            _product.Description = product.Description;
            _product.categoryID = product.categoryID;

            chocoPlanetDbEntities.SaveChanges();
            return RedirectToAction("SecurityProductCatalog");
        }
        [HttpGet]
        [Authorize(Roles = "Администратори")]
        public ActionResult Create()
        {
            ViewData["Category"] = new SelectList(chocoPlanetDbEntities.Category, "ID", "Name"); ;
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Администратори")]
        public ActionResult Create(Product product, string photo_filename)
        {
            product.Foto = _fileStore.UploadFolderAbsolute + photo_filename;
            chocoPlanetDbEntities.AddToProduct(product);
            chocoPlanetDbEntities.SaveChanges();
            return RedirectToAction("SecurityProductCatalog");
        }
        [Authorize(Roles = "Администратори")]
        public ActionResult Delete(int id)
        {
            Product product = chocoPlanetDbEntities.Product.SingleOrDefault(p => p.ID == id);
            chocoPlanetDbEntities.Product.DeleteObject(product);
            chocoPlanetDbEntities.SaveChanges();
            return RedirectToAction("SecurityProductCatalog");
        }
        [Authorize(Roles = "Администратори")]
        public IQueryable<Product> GetAllProductOrFilter(int categoryId)
        {
            IQueryable<Product> products;
            if (categoryId == 0)
            {
                products = chocoPlanetDbEntities.Product;
            }
            else
            {
                products = chocoPlanetDbEntities.Product.Where(p => p.categoryID == categoryId);
            }
            return products;
        }
    }
}

trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
      <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>  
   
        <script src="../../Scripts/swfupload.js"></script>
        <script src="../../Scripts/jquery-asyncUpload-0.1.js"></script>
       

 
<script  type="text/javascript">
    $(function () {
        $("#photo").makeAsyncUploader({
            upload_url: "/Product/GetFileName",
            flash_url: '/Scripts/swfupload.swf',
            button_image_url: '/Content/blankButton.png',
            disableDuringUpload: 'INPUT[type="submit"]'
        });
    });        
</script>
  
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>
                    CHOCOPLANET</h1>
            </div>
             @if (!(ViewContext.Controller is ChocoPlanet.Controllers.CartController))
                {
                    Html.RenderAction("Summary", "Cart");
                }
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")                 
            </div>
          
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Домашня сторінка", "Index", "Home")</li>
                    <li>@Html.ActionLink("Каталог продукції", "ProductCatalog", "Product")</li>
                    <li>@Html.ActionLink("Про програму", "About", "Home")</li>
                    @if (Roles.IsUserInRole(HttpContext.Current.User.Identity.Name, "Администратори"))
                    {
                        <li>@Html.ActionLink("Адміністрування", "CategoryCatalog", "Category")</li>
                        <li>@Html.ActionLink("Замовлення", "Index", "Order")</li>
                        
                    }
                </ul>
            </div>
        </div>
        <div id="main">
           
                @RenderBody()
           
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Ласкаво просимо <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Views/Shared/_Security.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Фунції</h2>
<div id="submenucontainer">
    <ul id="submenu">
        <li>@Html.ActionLink("Категорії", "CategoryCatalog", "Category")</li>
       <li>@Html.ActionLink("Каталог продукції", "SecurityProductCatalog", "Product")</li>
        @* <li>@Html.ActionLink("Про програму", "About", "Home")</li>
        <li>@Html.ActionLink("Адміністрування", "ListOptions", "Administrator")</li>*@
    </ul>
</div>
@RenderBody()
