trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ChocoPlanet.Models
{
    [MetadataType(typeof(ProductValidation))]
    public partial class Product
    {
    }

    public class ProductValidation
    {
       [Required(ErrorMessage = "Поле не може бути пустим!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Поле не може бути пустим!")]
        public string Price { get; set; }
        [Required(ErrorMessage = "Поле не може бути пустим!")]
        public string Description { get; set; }
    }
}

trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using ChocoPlanet.Core;
using ChocoPlanet.Models;


namespace ChocoPlanet.Controllers
{
    [HandleErrors]
    public class NavController : Controller
    {
        
        private ChocoPlanetDbEntities chocoPlanetDbEntities;
        public NavController(ChocoPlanetDbEntities chocoPlanetDbEntities)
        {
           
            this.chocoPlanetDbEntities = chocoPlanetDbEntities;
        }

        public ActionResult Menu(string highlightCategory)
        {
            List<NavLink> navLinks = new List<NavLink>();
            navLinks.Add(new CategoryLink(null)
            {isSelected = (highlightCategory==null)});
            var categories = chocoPlanetDbEntities.Category.Select(x => x.Name);
            foreach (string category in categories.OrderBy(x=>x))
            {
                navLinks.Add(new CategoryLink(category)
                { isSelected = (category == highlightCategory ) });


            }
            return PartialView(navLinks);
            

        }

    }

    public class NavLink
    {
        public string Text { get; set; }
        public RouteValueDictionary RouteValues { get; set; }
        public bool isSelected { get; set; }
    }
    public class CategoryLink : NavLink
    {
        public CategoryLink(string category)
        {
            Text = category ?? "Вся продукція";
            RouteValues = new RouteValueDictionary(new
                                                       {
                                                           controller = "Product",
                                                           action = "ProductCatalog",
                                                           category = category,
                                                           page = 1

                                                       });
        }
    }
}

trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChocoPlanet.Core;
using ChocoPlanet.Models;
using ChocoPlanet.Models.File;

namespace ChocoPlanet.Controllers
{
    [HandleErrors]
    public class ProductController : Controller
    {
        //private readonly DataManager _dataManager;
        private readonly ChocoPlanetDbEntities chocoPlanetDbEntities;


        private ViewResult viewResultProduct;
        private IFileStore _fileStore = new DiskFileStore();
        public int PageSize = 1;
        public ViewResult ViewResultProduct { get; private set; }


        public string GetFileName()
        {

            return _fileStore.SaveUploadedFile(Request.Files[0]);
        }
        public ProductController(ChocoPlanetDbEntities chocoPlanetDbEntities)
        {

            this.chocoPlanetDbEntities = chocoPlanetDbEntities;


        }

        public ActionResult ProductCatalog(string category, int page)
        {
            int categoryId = 0;
            IQueryable<Product> productsInCategory;
            if (!string.IsNullOrEmpty(category))
            {
                categoryId = chocoPlanetDbEntities.Category.SingleOrDefault(c => c.Name == category).ID;
            }
            productsInCategory =
                GetAllProductOrFilter(categoryId).OrderBy(x => x.ID).Skip((page - 1) * PageSize).Take(PageSize);

            ViewResultProduct = View(productsInCategory.ToList());
            int numProduct = GetAllProductOrFilter(categoryId).Count();
            ViewData["TotalPages"] = (int)Math.Ceiling((double)numProduct / PageSize);
            ViewData["CurrentPage"] = page;

            ViewData["CurrentCategory"] = (string.IsNullOrEmpty(category)) ? string.Empty : chocoPlanetDbEntities.Category.SingleOrDefault(p => p.ID == categoryId).Name;

            return ViewResultProduct;

        }
        [Authorize(Roles = "Администратори")]
        public ActionResult SecurityProductCatalog([Bind(Include = "ID")]Category category)
        {
            ViewData["ID"] = new SelectList(chocoPlanetDbEntities.Category, "ID", "Name");
            ViewResultProduct = View(GetAllProductOrFilter(category.ID));
            return ViewResultProduct;
        }
        [HttpGet]
        [Authorize(Roles = "Администратори")]
        public ActionResult Edit(int id)
        {
            Product product = chocoPlanetDbEntities.Product.SingleOrDefault(p => p.ID == id);
            ViewData["Category"] = new SelectList(chocoPlanetDbEntities.Category, "ID", "Name"); ;
            return View(chocoPlanetDbEntities.Product.SingleOrDefault(p => p.ID == id));
        }
        [HttpPost]
        [Authorize(Roles = "Администратори")]
        public ActionResult Edit(int id, Product product, string photo_filename)
        {
            Product _product = chocoPlanetDbEntities.Product.SingleOrDefault(p => p.ID == product.ID);
            _product.Name = product.Name;
            if (!String.IsNullOrEmpty(photo_filename))
                _product.Foto = _fileStore.UploadFolderAbsolute + photo_filename;
            _product.Price = product.Price;
            _product.Description = product.Description;
            _product.categoryID = product.categoryID;

            chocoPlanetDbEntities.SaveChanges();
            return RedirectToAction("SecurityProductCatalog");
        }
        [HttpGet]
        [Authorize(Roles = "Администратори")]
        public ActionResult Create()
        {
            ViewData["Category"] = new SelectList(chocoPlanetDbEntities.Category, "ID", "Name"); ;
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Администратори")]
        public ActionResult Create(Product product, string photo_filename)
        {
            product.Foto = _fileStore.UploadFolderAbsolute + photo_filename;
            chocoPlanetDbEntities.AddToProduct(product);
            chocoPlanetDbEntities.SaveChanges();
            return RedirectToAction("SecurityProductCatalog");
        }
        [Authorize(Roles = "Администратори")]
        public ActionResult Delete(int id)
        {
            Product product = chocoPlanetDbEntities.Product.SingleOrDefault(p => p.ID == id);
            chocoPlanetDbEntities.Product.DeleteObject(product);
            chocoPlanetDbEntities.SaveChanges();
            return RedirectToAction("SecurityProductCatalog");
        }
        [Authorize(Roles = "Администратори")]
        public IQueryable<Product> GetAllProductOrFilter(int categoryId)
        {
            IQueryable<Product> products;
            if (categoryId == 0)
            {
                products = chocoPlanetDbEntities.Product;
            }
            else
            {
                products = chocoPlanetDbEntities.Product.Where(p => p.categoryID == categoryId);
            }
            return products;
        }
    }
}

trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Views/Product/Create.cshtml
@model ChocoPlanet.Models.Product
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Security.cshtml";
}
<h2>
    Create</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    
    
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)    <fieldset>
        <legend>Product</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Foto)
        </div>
        <div class="editor-field">
            <input type="file" id="photo" name="photo" />
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.categoryID)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.categoryID, (IEnumerable<SelectListItem>)ViewData["Category"])
            @Html.ValidationMessageFor(model => model.categoryID)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Назад", "SecurityProductCatalog")
</div>

trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Views/Product/Edit.cshtml
@model ChocoPlanet.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Security.cshtml";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Product</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Foto)
        </div>
        <div class="editor-field">
            <div class="editor-field">
            <input type="file" id="photo" name="photo" />
        </div>
            @Html.ValidationMessageFor(model => model.Foto)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.DropDownListFor(m => m.categoryID, (IEnumerable<SelectListItem>)ViewData["Category"])
            @*@Html.DropDownList("Category", (IEnumerable<SelectListItem>)ViewData["Category"])*@
        </div>
      

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Назад", "SecurityProductCatalog")
</div>


trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Views/Product/ProductCatalog.cshtml
@model IEnumerable<ChocoPlanet.Models.Product>
@using ChocoPlanet.HtmlHelpers
<div id="categories">
    @{Html.RenderAction("Menu", "Nav", new { highlightCategory = @ViewData["CurrentCategory"] });}
</div>
<div id="content">
    <h2>
        Каталог продукції:
        @if (string.IsNullOrEmpty((string)ViewData["CurrentCategory"]))
        {
            <text> Вся продукція</text>
        }
        else
        { @ViewData["CurrentCategory"] }
    </h2>
    <p>
    </p>
    <br />
    <table>
        <tr>
            <th>
                Назва
            </th>
            <th>
                Описання
            </th>
            <th>
                Фото
            </th>
            <th>
                Ціна
            </th>
            <th>
                Корзина
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td width="10%">
                    @item.Name
                </td>
                <td width="0%">
                    @item.Description
                </td>
                <td width="10%">
                    <img src="@Url.Content(@item.Foto)" height="260px"/>
                </td>
                <td width="10%">
                    @item.Price
                </td>
                <td>
                    @using (Html.BeginForm("AddToCart", "Cart"))
                    {
                    
                        @Html.Hidden("ID", item.ID)
                        @Html.Hidden("returnUrl", ViewContext.HttpContext.Request.Url.PathAndQuery)
                        <input type="submit" value="+Додати до корзини" />
                    }
                </td>
            </tr>
        }
    </table>

<div class="pager">
    Page:
    @Html.PageLinks((int)ViewData["CurrentPage"], (int)ViewData["TotalPages"], x => Url.Action("ProductCatalog", new { page = x, category = ViewData["CurrentCategory"] }))
</div>
</div>

trunk/02-UserDirs/Pinchuk/Dom/ASP.NET/ChocoPlanet/ChocoPlanet/Views/Product/SecurityProductCatalog.cshtml
@model IEnumerable<ChocoPlanet.Models.Product>
@{
    ViewBag.Title = "ProductCatalog";
    Layout = "~/Views/Shared/_Security.cshtml";
}
<h2>
    ProductCatalog</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (@Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "listProduct", OnSuccess = "ajaxOnSuccess", Confirm = "dsd" }))
{
    <p>
        @Html.DropDownList("ID", null, "-= Примінити фільтр по категоріям =-", new { onchange = "this.form.submit();", onload = "this.form.submit();" })
    </p>
   
    <br />
    <div id="listProduct">
        <table>
            <tr>
                <th>
                </th>
                <th>
                    Назва
                </th>
                <th>
                    Описання
                </th>
                <th>
                    Фото
                </th>
                <th>
                    Ціна
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td width="80px">
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |                       
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { onclick = "return confirm('Ви впевнені що хочете видилити');" })
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        <img src="@Url.Content(@item.Foto)"  height="260px"  />
                    </td>
                    <td>
                        @item.Price
                    </td>
                </tr>
            }
        </table>
    </div>
}